{{- if .Values.serviceMonitoring.enabled -}}
---
apiVersion: {{ .Values.serviceMonitoring.apiVersion }}
kind: {{ .Values.serviceMonitoring.kind }}
metadata:
  name: {{ include "app.name" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: http
      scheme: http
      path: /metrics
  jobLabel: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
