// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package users_test is a generated GoMock package.
package users_test

import (
	context "context"
	reflect "reflect"

	database "github.com/ft-t/go-money/pkg/database"
	gomock "github.com/golang/mock/gomock"
)

// MockJwtSvc is a mock of JwtSvc interface.
type MockJwtSvc struct {
	ctrl     *gomock.Controller
	recorder *MockJwtSvcMockRecorder
}

// MockJwtSvcMockRecorder is the mock recorder for MockJwtSvc.
type MockJwtSvcMockRecorder struct {
	mock *MockJwtSvc
}

// NewMockJwtSvc creates a new mock instance.
func NewMockJwtSvc(ctrl *gomock.Controller) *MockJwtSvc {
	mock := &MockJwtSvc{ctrl: ctrl}
	mock.recorder = &MockJwtSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtSvc) EXPECT() *MockJwtSvcMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJwtSvc) GenerateToken(arg0 context.Context, user *database.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJwtSvcMockRecorder) GenerateToken(arg0, user interface{}) *JwtSvcGenerateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwtSvc)(nil).GenerateToken), arg0, user)
	return &JwtSvcGenerateTokenCall{Call: call}
}

// JwtSvcGenerateTokenCall wrap *gomock.Call
type JwtSvcGenerateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *JwtSvcGenerateTokenCall) Return(arg0 string, arg1 error) *JwtSvcGenerateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *JwtSvcGenerateTokenCall) Do(f func(context.Context, *database.User) (string, error)) *JwtSvcGenerateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *JwtSvcGenerateTokenCall) DoAndReturn(f func(context.Context, *database.User) (string, error)) *JwtSvcGenerateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
