image:
  repository: ghcr.io/ft-t/go-money/go-money-server
  pullPolicy: IfNotPresent
  tag: "0.2.0"

imagePullSecrets:

nameOverride: ""
fullnameOverride: ""

serviceMonitoring:
  enabled: true
  apiVersion: v1beta1

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  port: 80
  grpc: 81

ingress:
  enabled: false
  profiler: false
  domain: "go-money.local"
  className: ""
  hosts:
    - host: go-money.local
      paths:
        - path: /
          pathType: Exact
  tls: [ ]

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: { }

tolerations: [ ]

affinity:
  
envFrom:
  configMaps:
  secrets:

env:
