http:
  routers:
    app:
      rule: "Host(`{{env "GO_MONEY_EXTERNAL_HOST"}}`)"
      service: app
      entryPoints:
        - web

    grafana:
      rule: "Host(`{{env "GRAFANA_EXTERNAL_HOST"}}`)"
      service: grafana
      entryPoints:
        - web

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:{{env "GRPC_PORT"}}"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:{{env "GRAFANA_PORT"}}"
